build_cmd :: use for both local and cvmfs compilation

diff --git a/build_cmd b/build_cmd
--- a/build_cmd
+++ b/build_cmd
@@ -1,22 +1,42 @@
 #!/usr/bin/env bash
 
-mkdir -p BUILD INSTALL
-rm -rf BUILD/*
+USE_LOCAL_SW=""
+export LOCAL_TAG="latest-o2physics-o2"
 
-export WORK_DIR="/cvmfs/alice.cern.ch" ALIBUILD_ARCH_PREFIX="el7-x86_64/Packages" DISABLE_GPU=1
-
-source "${WORK_DIR}"/"${ALIBUILD_ARCH_PREFIX}"/JAliEn-ROOT/0.6.6-124/etc/profile.d/init.sh
-source "${WORK_DIR}"/"${ALIBUILD_ARCH_PREFIX}"/libjalienO2/0.1.3-20/etc/profile.d/init.sh
-source "${WORK_DIR}"/"${ALIBUILD_ARCH_PREFIX}"/O2Physics/nightly-20220522-1/etc/profile.d/init.sh
-
-CMAKE_DEBUG_OPTS=""
+CMAKE_DEBUG_OPTS="1"
 [[ -n ${CMAKE_DO_TRACE} ]] && CMAKE_DEBUG_OPTS=" --debug-output --debug-find --trace --trace-expand --trace-format=human --trace-redirect=cmake_trace.log "
+
+mkdir -p BUILD INSTALL
+rm -rf BUILD/* INSTALL/*
+
+if [[ -n "${USE_LOCAL_SW}" ]]; then
+    export O2PHYS_TAG="${LOCAL_TAG}"
+    export WORK_DIR="${ALIBUILD_WORK_DIR}" ALIBUILD_ARCH_PREFIX="$(aliBuild architecture)" DISABLE_GPU=1
+else
+    export O2PHYS_TAG="nightly-20221027-1"
+    export WORK_DIR="/cvmfs/alice.cern.ch" ALIBUILD_ARCH_PREFIX="el7-x86_64/Packages" DISABLE_GPU=1
+fi
+
+if [[ -n "${USE_LOCAL_SW}" ]]; then
+    source ${WORK_DIR}/${ALIBUILD_ARCH_PREFIX}/XRootD/${O2PHYS_TAG}/etc/profile.d/init.sh
+fi
+
+# source ${WORK_DIR}/${ALIBUILD_ARCH_PREFIX}/JAliEn-ROOT/${BUILD_TAG}/etc/profile.d/init.sh
+# source ${WORK_DIR}/${ALIBUILD_ARCH_PREFIX}/libjalienO2/${BUILD_TAG}/etc/profile.d/init.sh
+# source ${WORK_DIR}/${ALIBUILD_ARCH_PREFIX}/O2/${BUILD_TAG}/etc/profile.d/init.sh
+source "${WORK_DIR}"/"${ALIBUILD_ARCH_PREFIX}"/O2Physics/${O2PHYS_TAG}/etc/profile.d/init.sh
+env > compilation_env.txt
 
 pushd BUILD
 cmake3 -DCMAKE_INSTALL_PREFIX=../INSTALL -DBUILD_TEST_ROOT_MACROS=OFF ${CMAKE_DEBUG_OPTS} \
     -DLIBJALIENO2_INCLUDE_DIR=${LIBJALIENO2_ROOT}/include -DLIBJALIENO2_LIBPATH=${LIBJALIENO2_ROOT}/lib/libjalienO2.so \
     -DJALIEN_ROOT_INCLUDE_DIR=${JALIEN_ROOT_ROOT}/include -DJAliEnRoot_LIB=${JALIEN_ROOT_ROOT}/lib/libJAliEnROOT.so \
-    ..
+    .. 
+
+RET=$?
+
+[[ "${RET}" == 0 ]] && make -j4 || { popd; echo "cmake failure"; exit ${RET}; }
+[[ "${RET}" == 0 ]] && make install || { popd;  echo "make failure"; exit ${RET}; }
 
 popd
 
