improve enable script

diff --git a/enable b/enable
--- a/enable
+++ b/enable
@@ -2,7 +2,7 @@
 
 ###   DEFAULTS   ###
 export LOCAL_TAG="latest-o2physics-o2"
-export CVMFS_TAG="daily-20250219-0000-1"
+export CVMFS_TAG="daily-20250605-0000-1"
 
 # Steering of the environment:
 #
@@ -10,6 +10,10 @@ export CVMFS_TAG="daily-20250219-0000-1"
 # O2OPENACCESS_SW_TAG_CVMFS : set the string name for CVMFS installation
 #
 # O2OPENACCESS_USE_LOCAL : set to anything to use the local tag (and installation) instead of CVMFS (which is the default)
+
+export O2OPENACCESS_USE_LOCAL=${O2OPENACCESS_USE_LOCAL:-}   # if set, use the local installation
+export O2OPENACCESS_SW_TAG_LOCAL=${O2OPENACCESS_SW_TAG_LOCAL:-${LOCAL_TAG}}
+export O2OPENACCESS_SW_TAG_CVMFS=${O2OPENACCESS_SW_TAG_CVMFS:-${CVMFS_TAG}}
 
 #####################################################
 
@@ -19,7 +23,7 @@ SCRIPT_PATH=$(realpath -e -P "${BASH_SOURCE[0]}")
 SCRIPT_DIR=$(cd -P $(dirname -- "${SCRIPT_PATH}") >/dev/null 2>&1 && pwd)
 
 ## HELPERS
-SourceIfValid () { [[ -f $1 ]] && source $1; }
+SourceIfValid () { [[ -f "${1}" ]] && source "${1}"; }
 
 # Check if 2nd arg is found in the list(terms delimited by ":") in the 1st arg
 ITEM_IN_PATH () {
@@ -34,49 +38,50 @@ return 1;
 }
 
 # Insert/Add to $PATH if and only if not already present
-__PATH_INS () { [[ -z "${1}" ]] && return 1; ITEM_IN_PATH "${PATH}" ${1} && return 0; export PATH="${1}${PATH:+:}${PATH}"; }
-__PATH_ADD () { [[ -z "${1}" ]] && return 1; ITEM_IN_PATH "${PATH}" ${1} && return 0; export PATH="${PATH}${PATH:+:}${1}"; }
-
-# Insert/Add to $LD_LIBRARY_PATH if and only if not already present
-__LDLIB_INS () { [[ -z "${1}" ]] && return 1; ITEM_IN_PATH "${LD_LIBRARY_PATH}" ${1} && return 0; export LD_LIBRARY_PATH="${1}${LD_LIBRARY_PATH:+:}${LD_LIBRARY_PATH}"; }
-__LDLIB_ADD () { [[ -z "${1}" ]] && return 1; ITEM_IN_PATH "${LD_LIBRARY_PATH}" ${1} && return 0; export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}${LD_LIBRARY_PATH:+:}${1}"; }
+__PATH_INS () { [[ -z "${1}" ]] && return 1; ITEM_IN_PATH "${PATH}" "${1}" && return 0; export PATH="${1}${PATH:+:}${PATH}"; }
+__PATH_ADD () { [[ -z "${1}" ]] && return 1; ITEM_IN_PATH "${PATH}" "${1}" && return 0; export PATH="${PATH}${PATH:+:}${1}"; }
 
 ######################################################################
 
-## if O2PHYSICS present (environemnt already enabled then just add path and exit)
+## if O2PHYSICS present (environemnt already enabled then just add path and return(we are sourced))
 [[ -n "${O2PHYSICS_ROOT}" ]] && { __PATH_INS "${SCRIPT_DIR}/bin" ; return 0 ; }
 
 # apply local customizations
-SourceIfValid ~/.aliopendata_cfg  # apply general customization user-level
 SourceIfValid ./.aliopendata_cfg  # apply local directory customization
 
-export O2OPENACCESS_USE_LOCAL=${O2OPENACCESS_USE_LOCAL:-}   # if set, use the local installation
-export O2OPENACCESS_SW_TAG_LOCAL=${O2OPENACCESS_SW_TAG_LOCAL:-${LOCAL_TAG}}
-export O2OPENACCESS_SW_TAG_CVMFS=${O2OPENACCESS_SW_TAG_CVMFS:-${CVMFS_TAG}}
-
+# construct location for etc/profile.d/init.sh
 if [[ -n "${O2OPENACCESS_USE_LOCAL}" ]]; then
     O2PHYS_TAG="${O2OPENACCESS_SW_TAG_LOCAL}"
-    export WORK_DIR="${ALIBUILD_WORK_DIR}" ALIBUILD_ARCH_PREFIX="$(aliBuild architecture)" DISABLE_GPU=1
-else
-    stat "/cvmfs/alice.cern.ch" &> /dev/null || { echo "CVMFS is not available!! >>> ${O2OPENACCESS_SW_TAG_CVMFS} <<< is not accessible!"; return 1; }
-    O2PHYS_TAG="${O2OPENACCESS_SW_TAG_CVMFS}"
-    export WORK_DIR="/cvmfs/alice.cern.ch" ALIBUILD_ARCH_PREFIX="el7-x86_64/Packages" DISABLE_GPU=1
-fi
-[[ -z "${O2PHYS_TAG}" ]] && { echo "O2PHYS_TAG is not set at this point, this should not happen!"; exit 1; }
+    WORK_DIR="${ALIBUILD_WORK_DIR}"
+    DISABLE_GPU=1
 
-NOT_FOUND=""
-O2PHYS_DIR="${WORK_DIR}/${ALIBUILD_ARCH_PREFIX}/O2Physics/${O2PHYS_TAG}"
-[[ ! -d "${O2PHYS_DIR}" ]] && { ALIBUILD_ARCH_PREFIX="el9-x86_64/Packages"; NOT_FOUND="1"; }
-
-if [[ -n "${NOT_FOUND}" ]]; then
+    ALIBUILD_ARCH_PREFIX="$(aliBuild architecture)"
     O2PHYS_DIR="${WORK_DIR}/${ALIBUILD_ARCH_PREFIX}/O2Physics/${O2PHYS_TAG}"
-    [[ ! -d "${O2PHYS_DIR}" ]] && { echo "O2Physics was not found in ${O2PHYS_DIR}"; exit 1; }
+    [[ ! -d "${O2PHYS_DIR}" ]] && { echo "O2PHYS_DIR ${O2PHYS_DIR} is not found"; return 1; }
+else
+    stat "/cvmfs/alice.cern.ch/bin" &> /dev/null || { echo "CVMFS is not available!! check for presence of /cvmfs/alice.cern.ch/bin!"; return 1; }
+    O2PHYS_TAG="${O2OPENACCESS_SW_TAG_CVMFS}"
+    WORK_DIR="/cvmfs/alice.cern.ch"
+    DISABLE_GPU=1
+
+    # check the arch of package
+    ALIBUILD_ARCH_PREFIX="el9-x86_64/Packages"
+    O2PHYS_DIR="${WORK_DIR}/${ALIBUILD_ARCH_PREFIX}/O2Physics/${O2PHYS_TAG}"
+
+    # it packages are not el9-x86_64/Packages let's try with el7-x86_64
+    if [[ ! -d "${O2PHYS_DIR}" ]]; then
+        ALIBUILD_ARCH_PREFIX="el7-x86_64/Packages"
+        O2PHYS_DIR="${WORK_DIR}/${ALIBUILD_ARCH_PREFIX}/O2Physics/${O2PHYS_TAG}"
+        [[ ! -d "${O2PHYS_DIR}" ]] && { echo "O2Physics was not found in ${O2PHYS_DIR}"; return 1; }
+    fi
 fi
+export WORK_DIR DISABLE_GPU O2PHYS_DIR
 
 O2PHYSICS_INIT="${O2PHYS_DIR}/etc/profile.d/init.sh"
 [[ ! -f "${O2PHYSICS_INIT}" ]] && { echo "${O2PHYSICS_INIT} not available"; return 1; }
 
-SourceIfValid "${O2PHYSICS_INIT}" &> /dev/null  # if we load from cvmfs ignore any errors
+source "${O2PHYSICS_INIT}" &> /dev/null  # if we load from cvmfs ignore any errors
 
+# add to PATH built executables
 __PATH_INS "${SCRIPT_DIR}/bin"
 
